name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build app for release
      run: msbuild SecurityPrivilegeCopy\SecurityPrivilegeCopy\EntityPrivilegeCopy.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
